#spring:
#  profiles:
#    active: local
#    include: real-oauth
#  datasource:
#    platform: mysql
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 1234
#    url: jdbc:mysql://localhost:3306/jpaexamplenk?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true&serverTimezone=UTC
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true
#    generate-ddl: true
#
#    hibernate:
#      ddl-auto: update

